name: run unit tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "go"
        ports:
          - "3306:3306"
    env:
      TZ: "Asia/Tokyo"

    steps:
      - name: sleep
        run: sleep 5s

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: module install
        run: go get -u github.com/kyoh86/richgo

      - name: run migrations
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv ./migrate.linux-amd64 /usr/bin/migrate
          make migrate

      - name: Test
        run: make rtest